# Generated by Django 5.2.4 on 2025-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
